package controller;

public enum Events {
    CREATE_PROCESS, START_SIMULATION, DELETE_PROCESS,EDIT_PROCESS,
    ADD_PROCESS, SHOW_EDIT_PROCESS,EXIT_PROCESS,
    EXIT_DIALOG_EXCEPTION, NEW_TRANSITION, EXIT_EDIT_PROCESS,SHOW_DELETE_PROCESS,EXIT_DElETE_PROCESS,
    EXIT, ENTER ;
}
